### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by holaymolay** [holaymolay/CartTools-Sinatra#21]
- [ ] Custom Domain
- [ ] Move Deals to separate list
- [ ] overcome timeout issue
- [ ] insert page link into spreadsheet
- [ ] implement ridumentary logging system & analytics
